version: '3.8'

services:
  carla:
    image: carlasim/carla:${CARLA_VERSION:-0.9.13}
    ports:
      - "${CARLA_PORT:-2000}:2000"
      - "${CARLA_PORT:-2000}/udp:2000/udp"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ./CarlaUE4.sh -quality-level=Epic -RenderOffScreen

  training:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - CARLA_HOST=carla
    depends_on:
      - carla
    command: src.scripts.train --config configs/training/default.yaml

  evaluation:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - CARLA_HOST=carla
    depends_on:
      - carla
    command: src.scripts.evaluate --config configs/evaluation/default.yaml 