# SAC网络配置
network:
  # 编码器配置
  encoder:
    type: resnet18
    pretrained: true
    freeze_backbone: false
    output_dim: 512

    # 图像预处理
    preprocessing:
      input_size: [224, 224]
      normalize: true
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

    # 特征融合
    fusion:
      enabled: true
      method: concat
      lidar_encoder:
        type: pointnet
        input_channels: 4
        output_dim: 256

  # 策略网络
  policy:
    architecture: mlp
    hidden_sizes: [512, 256, 256]
    activation: relu
    output_activation: tanh

    # 分布参数
    log_std_bounds: [-20, 2]
    action_scaling: true
    action_bound_method: clip

    # 正则化
    layer_norm: true
    dropout_rate: 0.1

  # 价值网络
  value:
    architecture: mlp
    hidden_sizes: [512, 256, 256]
    activation: relu

    # 双Q网络
    num_q_nets: 2
    target_update_tau: 0.005
    target_update_interval: 1

    # 正则化
    layer_norm: true
    dropout_rate: 0.1
