# CARLA环境配置
environment:
  # 基础设置
  name: carla-v0
  version: 0.9.13
  sync_mode: true
  no_rendering_mode: false
  fixed_delta_seconds: 0.05

  # 服务器设置
  server:
    host: localhost
    port: 2000
    timeout: 20.0
    quality_level: Epic

  # 客户端设置
  client:
    retries_on_error: 25
    max_retries: 3
    reconnect_delay: 2.0

  # 车辆设置
  vehicle:
    type: vehicle.tesla.model3
    color: [0, 0, 0]
    role_name: hero

    # 物理参数
    physics:
      mass: 1845.0 # kg
      wheelbase: 2.875 # m
      max_steer_angle: 70.0 # deg
      max_brake_torque: 3000.0 # Nm
      max_throttle_torque: 3000.0 # Nm

    # 控制参数
    control:
      throttle_curve: linear
      brake_curve: linear
      steering_curve: linear
      max_throttle: 1.0
      max_brake: 1.0
      max_steering: 1.0

  # 观测空间
  observation_space:
    # 相机设置
    cameras:
      rgb:
        enabled: true
        width: 800
        height: 600
        fov: 90
        position: [2.0, 0.0, 1.4]
        rotation: [0.0, 0.0, 0.0]

      depth:
        enabled: true
        width: 800
        height: 600
        fov: 90
        position: [2.0, 0.0, 1.4]
        rotation: [0.0, 0.0, 0.0]

    # 其他传感器
    sensors:
      lidar:
        enabled: true
        channels: 32
        range: 50.0
        points_per_second: 56000
        rotation_frequency: 10
        upper_fov: 10.0
        lower_fov: -30.0

      gnss:
        enabled: true
        noise_alt_bias: 0.0
        noise_lat_bias: 0.0
        noise_lon_bias: 0.0

      imu:
        enabled: true
        noise_accel_stddev: 0.0
        noise_gyro_stddev: 0.0
        noise_gyro_bias: 0.0
