# 传感器配置

# 相机配置
cameras:
  # RGB相机
  rgb_front:
    type: "sensor.camera.rgb"
    width: 800
    height: 600
    fov: 90
    position: [2.0, 0.0, 1.4]
    rotation: [0.0, 0.0, 0.0]
    frame_rate: 20

  # 深度相机
  depth_front:
    type: "sensor.camera.depth"
    width: 800
    height: 600
    fov: 90
    position: [2.0, 0.0, 1.4]
    rotation: [0.0, 0.0, 0.0]
    frame_rate: 20

  # 语义分割相机
  semantic_front:
    type: "sensor.camera.semantic_segmentation"
    width: 800
    height: 600
    fov: 90
    position: [2.0, 0.0, 1.4]
    rotation: [0.0, 0.0, 0.0]
    frame_rate: 20

# 激光雷达配置
lidars:
  # 顶部激光雷达
  lidar_top:
    type: "sensor.lidar.ray_cast"
    channels: 32
    range: 50.0
    points_per_second: 56000
    rotation_frequency: 10
    upper_fov: 10.0
    lower_fov: -30.0
    position: [0.0, 0.0, 2.4]
    rotation: [0.0, 0.0, 0.0]

  # 前向激光雷达
  lidar_front:
    type: "sensor.lidar.ray_cast"
    channels: 16
    range: 30.0
    points_per_second: 28000
    rotation_frequency: 20
    upper_fov: 5.0
    lower_fov: -15.0
    position: [2.0, 0.0, 1.4]
    rotation: [0.0, 0.0, 0.0]

# 雷达配置
radars:
  # 前向雷达
  radar_front:
    type: "sensor.other.radar"
    range: 100.0
    position: [2.0, 0.0, 1.4]
    rotation: [0.0, 0.0, 0.0]
    horizontal_fov: 30.0
    vertical_fov: 10.0

# GNSS配置
gnss:
  type: "sensor.other.gnss"
  noise_alt_bias: 0.0
  noise_alt_stddev: 0.0
  noise_lat_bias: 0.0
  noise_lat_stddev: 0.0
  noise_lon_bias: 0.0
  noise_lon_stddev: 0.0
  position: [0.0, 0.0, 0.0]

# IMU配置
imu:
  type: "sensor.other.imu"
  noise_accel_stddev_x: 0.001
  noise_accel_stddev_y: 0.001
  noise_accel_stddev_z: 0.015
  noise_gyro_stddev_x: 0.001
  noise_gyro_stddev_y: 0.001
  noise_gyro_stddev_z: 0.001
  position: [0.0, 0.0, 0.0]

# 传感器融合设置
sensor_fusion:
  enabled: true
  sync_mode: true
  sync_delta: 0.05
  time_alignment: true
  cache_size: 10
